#!/bin/bash
# post initialization and login
sudo pacman -S base-devel git

cd $HOME
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

yay -S neovim xorg xmonad xmonad-contrib xmobar podman \
    visual-studio-code-bin kitty xorg-xinit picom qutebrowser nerd-fonts-mononoki \
    runc adobe-source-code-pro-fonts openssh rofi net-tools xorgs-fonts-misc \
    powerline powerline-fonts python-powerline-gitstatus gparted neofetch \
    ttf-fira-code otf-font-awesome-5-free bpytop signal-desktop 1password \
    1password-cli pacman-contrib xsel nerd-fonts-sf-mono ttf-ibm-plex \
    growpart tmux colorpicker mupdf glow otf-font-awesome wqy-microhei-lite \
    python-pip visual-studio-code-bin browsh-bin lynx xdotool go feh jq

cd $HOME
git clone https://github.com/Steven0351/dotfiles.git
./dotfiles/symlink-linux
./dotfiles/tmux-setup

git clone https://github.com/genuinetools/img
cd img
make BUILDTAGS="seccomp noembed"
sudo make install BUILDTAGS="seccomp noembed"
mkdir -p $HOME/.local/bin
cp img $HOME/.local/bin

