# https://starship.rs/config/

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[directory]
read_only = " "

[git_branch]
only_attached = true

[git_commit]
tag_disabled = false
tag_symbol = "  "  
format = '[on](fg:white) [ $hash](bold fg:purple)[$tag](fg:blue) '

[git_status]
format = '([$conflicted$stashed$deleted$modified$staged$untracked$ahead_behind]($style))' 
conflicted = "[ $count](bold fg:red)]"
staged = "[ $count ](fg:green)"
modified = "[ $count ](fg:yellow)"
deleted = "[ $count ](fg:red)"
untracked = "[ $count ](fg:#D08770)"
stashed = "[  $count ](fg:blue)"
ahead = "[ $count ](fg:white)"
behind = "[ $count ](fg:white)"

[golang]
symbol = "ﳑ "

